---
name: Lint and test
on:
  pull_request:

env:
  PYTHON_VERSION: '3.10'
  POETRY_VERSION: '2.0.1'
jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: snok/install-poetry@v1
        with:
            version: ${{ env.POETRY_VERSION }}
            virtualenvs-create: false
      - name: Install dependencies and run lints
        run: |
          # Necessary for running the mypy pre-commit hook
          poetry config virtualenvs.create false
          poetry sync
      - name: Linting and static code checks
        continue-on-error: true
        id: pre-commit-first-run
        uses: pre-commit/action@v3.0.1
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        id: auto-commit-action
        with:
          create_branch: false
          commit_message: Linting and static code checks
      # If the first run failed, run the checks again to ensure that the changes fixed the issue.
      - name: Linting and static code checks try 2
        if: steps.pre-commit-first-run.outcome != 'success'
        uses: pre-commit/action@v3.0.1
