---
name: Lint and test
on:
  pull_request:
    types: [opened, edited]

env:
  PYTHON_VERSION: '3.10'
  POETRY_VERSION: '2.0.1'

jobs:
  validate-description:
    name: Validate PR description
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
          virtualenvs-create: false
      - name: Install dependencies
        run: poetry sync
      - name: Dump description to file
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const description = context.payload.pull_request.body;
            fs.writeFileSync('last_git_message.txt', description);
      - name: Inspect Description File
        run: cat last_git_message.txt
      - name: Validate Changelog section in PR description
        run: python dev.py changelog
