name: Release Toolkit
on:
  push:
    branches:
      - main
env:
  PYTHON_VERSION: '3.11'
  POETRY_VERSION: '2.0.1'

jobs:
  release-pypi:
    runs-on: ubuntu-latest
    environment: CD
    # This causes issues when CDF is down.
    #needs: [lint, test, build]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
          virtualenvs-create: false
      - name: Install dependencies
        run: poetry sync
      - name: Dump last commit message to file
        run: git log -1 --pretty=%B > last_git_message.txt
      - name: Dump last tag to file
        run: git describe --tags --abbrev=0 > last_version.txt
      - name: Bump Version
        run: python dev.py bump --verbose
      - name: Create CHANGELOG entry
        run: python dev.py changelog
      - id: version
        name: Read the new version
        # Read the version from the cognite_toolkit/_version.py file
        run: echo "version=$(sed -n 's/^__version__ = "\(.*\)"/\1/p' cognite_toolkit/_version.py)" >> $GITHUB_ENV
      - name: Build package
        run: poetry build
      - name: Release to PyPI
#        env:
#          TWINE_USERNAME: __token__
#          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
#        run: twine upload --skip-existing  --verbose dist/*
        run: echo "Would release to PyPI"
      - name: Add entry to CHANGELOG
        uses: ncipollo/release-action@v1
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            prerelease: false
            draft: false
            tag: ${{ env.version }}
            bodyFile: last_changelog_entry.md
